Repository Shared-Milk/shared-milk-ui, pull requests merged in 2022-03, with the labels that each got.

#22 Feature/create cypress testing cag
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/landing_page_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: testing

#26 Circleci project setup-cag
  .circleci/config.yml
Labels: testing

#31 Feature/initial styling setup jp
  public/index.html
  src/Styles/Reset.scss
  src/Styles/_mixins.scss
  src/Styles/_variables.scss
Labels: FE

#32 Feature/header and footer components
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/App/App.scss
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/HomePage/HomePage.js
  src/Components/Styles/Reset.scss
  src/Components/Styles/_mixins.scss
  src/Components/Styles/_variables.scss
  src/index.js
Labels: FE

#33 Feature/home page
  public/favicon.ico
  public/index.html
  src/Components/App/App.js
  src/Components/App/App.scss
  src/Components/ConfirmationMessage/ConfirmationMessage.scss
  src/Components/DonateMilk/DonateMilk.scss
  src/Components/DonateMilkForm/DonateMilkForm.scss
  src/Components/Footer/Footer.js
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/HomePage/HomePage.js
  src/Components/HomePage/HomePage.scss
  src/Components/MilkRequestForm/MilkRequestForm.scss
  src/Components/NeedMilk/NeedMilk.scss
  src/Components/NoDonorMessage/NoDonorMessage.scss
  src/Components/Styles/_mixins.scss
  src/Components/SupportPage/SupportPage.scss
Labels: FE

#36 Update app name throughout site
  public/index.html
  src/Components/Footer/Footer.js
  src/Components/Header/Header.js
Labels: FE

#52 Feature/pass state link-cag
  package-lock.json
  src/Components/DonateMilkForm/DonateMilkForm.js
  src/Components/DonorCard/DonorCard.js
  src/Components/Header/Header.js
  src/Components/HomePage/HomePage.js
  src/Components/MilkRequestForm/MilkRequestForm.js
  src/Components/NeedMilk/NeedMilk.js
  src/Graphql/Queries.js
Labels: mvp

#53 Add mission statement
  src/Components/HomePage/HomePage.js
  src/Components/NeedMilk/NeedMilk.js
Labels: mvp

#54 Refactor sass
  src/Components/DonateMilk/DonateMilk.js
  src/Components/DonateMilk/DonateMilk.scss
  src/Components/HomePage/HomePage.scss
  src/Components/NeedMilk/NeedMilk.js
  src/Components/NeedMilk/NeedMilk.scss
  src/Components/SupportPage/Support.js
  src/Components/SupportPage/Support.scss
Labels: mvp

#63 Refactor/form styling jp
  src/Components/DonateMilkForm/DonateMilkForm.js
  src/Components/MilkRequestForm/MilkRequestForm.js
  src/Components/MilkRequestForm/MilkRequestForm.scss
Labels: FE

#61 Feature/cypress support dc
  cypress/integration/support_page_spec.js
  src/Components/Header/Header.js
  src/Components/SupportLink/SupportLink.js
  src/Components/SupportPage/Support.js
Labels: FE

#65 Feature/hamburger menu jp
  cypress/integration/landing_page_spec.js
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/App/App.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/MobileMenu/MobileMenu.js
  src/Components/MobileMenu/MobileMenu.scss
Labels: FE

#67 Feature/location only form jp
  src/Components/DonateMilkForm/DonateMilkForm.js
  src/Graphql/Mutations.js
Labels: FE

#70 Bugfix/graph ql be merge jp
  src/Components/DonateMilkForm/DonateMilkForm.js
  src/Graphql/Mutations.js
  src/Graphql/Queries.js
Labels: FE

#71 Update NeedMilk useEffect to correctly set user data
  src/Components/NeedMilk/NeedMilk.js
  src/Graphql/Queries.js
Labels: FE
