Repository Shared-Milk/shared-milk-ui, pull requests merged in 2022-04, with the labels that each got.

#90 Feature/about us page jp
  cypress/integration/landing_page_spec.js
  cypress/integration/support_page_spec.js
  public/logo512.png
  src/Components/About/About.js
  src/Components/About/About.scss
  src/Components/About/AboutPage/About.js
  src/Components/About/AboutPage/About.scss
  src/Components/About/MemberCard/MemberCard.js
  src/Components/About/ProfilePage/Profile.js
  src/Components/About/ProfilePage/Profile.scss
  src/Components/About/TeamMembers/TeamMembers.js
  src/Components/App/App.js
  src/Components/DonorCard/DonorCard.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/HomePage/HomePage.js
  src/Components/MilkRequestForm/MilkRequestForm.scss
  src/Components/MobileMenu/MobileMenu.js
  src/Components/Styles/_mixins.scss
  src/Components/SupportLink/SupportLink.scss
  src/TeamData/Images/chez_gallo.png
  src/TeamData/Images/devon_wigle.png
  src/TeamData/Images/eric_mielke.png
  src/TeamData/Images/jani_palomino.png
  src/TeamData/Images/kelly_anderson.png
  src/TeamData/Images/lindsay_schnell.png
  src/TeamData/Images/seth_perna.png
  src/TeamData/SocialIcons/github.png
  src/TeamData/SocialIcons/linkedin.png
  src/TeamData/SocialIcons/mail.png
  src/TeamData/TeamData.js
Labels: FE

#95 Refactor/media queries jp
  cypress/integration/landing_page_spec.js
  src/Components/About/AboutPage/About.js
  src/Components/About/AboutPage/About.scss
  src/Components/About/MemberCard/MemberCard.js
  src/Components/About/ProfilePage/Profile.js
  src/Components/About/ProfilePage/Profile.scss
  src/Components/App/App.scss
  src/Components/DonateMilk/DonateMilk.js
  src/Components/DonorCard/DonorCard.scss
  src/Components/Footer/Footer.js
  src/Components/Header/Header.scss
  src/Components/HomePage/HomePage.js
  src/Components/HomePage/HomePage.scss
  src/Components/MilkRequestForm/MilkRequestForm.scss
  src/Components/NeedMilk/NeedMilk.js
  src/Components/SupportLink/SupportLink.scss
  src/TeamData/TeamData.js
Labels: FE, Design Task

#97 Feature/add proptypes about us cag
  src/Components/About/MemberCard/MemberCard.js
  src/Components/About/TeamMembers/TeamMembers.js
Labels: enhancement, FE

#100 Tweak forms and sass for accessibility audit
  src/Components/About/ProfilePage/Profile.scss
  src/Components/App/App.scss
  src/Components/DonateMilk/DonateMilk.js
  src/Components/DonateMilkForm/DonateMilkForm.js
  src/Components/MilkRequestForm/MilkRequestForm.js
  src/Components/MilkRequestForm/MilkRequestForm.scss
  src/Components/SupportLink/SupportLink.scss
Labels: enhancement, FE

#101 Refactore/mobile menu jp
  cypress/integration/landing_page_spec.js
  src/Components/Header/Header.js
  src/Components/MobileMenu/MobileMenu.scss
Labels: FE, Design Task

#102 Feature/loading and error messages jp
  cypress/integration/landing_page_spec.js
  package-lock.json
  package.json
  src/Components/HomePage/HomePage.scss
  src/Components/NeedMilk/NeedMilk.js
Labels: enhancement, FE

#96 Feature/need milk test cag
  cypress/fixtures/donorMoms.json
  cypress/fixtures/example.json
  cypress/integration/need_milk_spec.js
  package-lock.json
  package.json
  src/Components/ConfirmationMessages/ConfirmationMessage.js
  src/Components/DonorCard/DonorCard.js
  src/Components/MilkRequestForm/MilkRequestForm.js
  src/Components/NeedMilk/NeedMilk.js
Labels: FE, testing

#106 Updated routing on profile pages to add to about pathname
  src/Components/About/MemberCard/MemberCard.js
  src/Components/About/ProfilePage/Profile.js
  src/Components/App/App.js
Labels: bug, FE

#105 Feature/cypress about page dw
  cypress/integration/about_page_spec.js
  cypress/integration/profile_page_spec.js
  src/Components/About/AboutPage/About.js
  src/Components/About/MemberCard/MemberCard.js
  src/Components/About/ProfilePage/Profile.js
  src/Components/About/TeamMembers/TeamMembers.js
  src/Components/Footer/Footer.js
  src/Components/Header/Header.js
Labels: FE, testing

#108 Clean up unneeded test ids, and refactor test
  cypress/integration/need_milk_spec.js
  src/Components/ConfirmationMessages/ConfirmationMessage.js
  src/Components/MilkRequestForm/MilkRequestForm.js
  src/Components/NeedMilk/NeedMilk.js
Labels: FE

#104 Feature/cypress header footer dw
  cypress/integration/about_page_spec.js
  cypress/integration/header_footer_spec.js
  cypress/integration/landing_page_spec.js
  cypress/integration/support_page_spec.js
  src/Components/Header/Header.js
  src/Components/HomePage/HomePage.js
Labels: FE, testing

#107 Feature/cypress donate milk 2 dw
  cypress/fixtures/createDonor.json
  cypress/integration/donate_milk_spec.js
  src/Components/ConfirmationMessages/DonorSorry.js
  src/Components/ConfirmationMessages/DonorThankYou.js
  src/Components/DonateMilk/DonateMilk.js
  src/Components/DonateMilkForm/DonateMilkForm.js
Labels: FE, testing

#110 Setup error handling component and state
  cypress/integration/donate_milk_spec.js
  src/Components/App/App.js
  src/Components/ConfirmationMessages/DonorThankYou.js
  src/Components/DonateMilkForm/DonateMilkForm.js
  src/Components/HomePage/HomePage.js
  src/Components/MilkRequestForm/MilkRequestForm.scss
  src/Components/NeedMilk/NeedMilk.js
  src/Components/NotFound/NotFound.js
  src/Components/NotFound/NotFound.scss
Labels: help wanted, FE

#114 Refactor/code clean up jp
  cypress/integration/about_page_spec.js
  src/Components/About/AboutPage/About.js
  src/Components/About/AboutPage/About.scss
  src/Components/About/MemberCard/MemberCard.js
  src/Components/About/ProfilePage/Profile.js
  src/Components/About/TeamMembers/TeamMembers.js
  src/Components/App/App.js
  src/Components/ConfirmationMessages/ConfirmationMessage.js
  src/Components/ConfirmationMessages/DonorSorry.js
  src/Components/ConfirmationMessages/DonorThankYou.js
  src/Components/DonateMilk/DonateMilk.js
  src/Components/DonateMilkForm/DonateMilkForm.js
  src/Components/DonorCard/DonorCard.js
  src/Components/DonorCard/DonorCard.scss
  src/Components/Footer/Footer.js
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/HomePage/HomePage.js
  src/Components/HomePage/HomePage.scss
  src/Components/MilkRequestForm/MilkRequestForm.js
  src/Components/MilkRequestForm/MilkRequestForm.scss
  src/Components/MobileMenu/MobileMenu.js
  src/Components/MobileMenu/MobileMenu.scss
  src/Components/NeedMilk/NeedMilk.js
  src/Components/NotFound/NotFound.js
  src/Components/NotFound/NotFound.scss
  src/Components/Styles/_mixins.scss
  src/Components/Styles/_variables.scss
  src/Components/SupportLink/SupportLink.js
  src/Components/SupportLink/SupportLink.scss
  src/Components/SupportPage/Support.js
Labels: FE

#116 Refactor/error handling cag
  src/Components/ConfirmationMessages/DonorThankYou.js
  src/Components/DonateMilkForm/DonateMilkForm.js
Labels: refactor

#118 Media query updates for mobile and tablet views
  src/Components/App/App.scss
  src/Components/DonorCard/DonorCard.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/MilkRequestForm/MilkRequestForm.scss
  src/Components/MobileMenu/MobileMenu.scss
Labels: enhancement, FE

#122 Refactor/UI updates jp
  cypress/integration/landing_page_spec.js
  src/Components/About/AboutPage/About.js
  src/Components/HomePage/HomePage.js
  src/Components/HomePage/HomePage.scss
  src/Components/MilkRequestForm/MilkRequestForm.scss
  src/Components/SupportLink/SupportLink.scss
  src/TeamData/TeamData.js
Labels: FE
